name: GitIdentities Module Tests

on:
  push:
    branches: [ master, develop, github-pipelines ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CI: true

jobs:

  test-powershell:
    name: Test PowerShell Module
    runs-on: windows-latest
    strategy:
      matrix:
        pwsh_shell: [powershell, pwsh]
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar en Windows PowerShell
        if: matrix.pwsh_shell == 'powershell'
        shell: powershell
        run: |
          & ./.github/workflows/scripts/Run-ModuleTests.ps1
      - name: Ejecutar en PowerShell Core
        if: matrix.pwsh_shell == 'pwsh'
        shell: pwsh
        run: |
          & ./.github/workflows/scripts/Run-ModuleTests.ps1